Repository plathanus-tech/django_boilerplate, pull requests merged in 2023-11, with the labels that each got.

#21 Feat/infra upgrades
  .github/workflows/deploy_to_production.yml
  .github/workflows/deploy_to_staging.yml
  .github/workflows/tests.yml
  README.md
  infra/app/Dockerfile
  infra/app/before_migrate.sh
  infra/nginx/conf.d/custom_proxy.conf
  infra/nginx/conf.d/fallback_server.conf
  infra/nginx/nginx.conf.template
  infra/server/3rd_party/production.yml
  infra/server/3rd_party/staging.yml
  infra/server/start_nginx_acme.sh
  infra/traefik/traefik.Dockerfile
  infra/traefik/traefik.yml
  local.yml
  production.yml
  staging.yml
Labels: enhancement

#22 Push Notifications API
  src/api/__init__.py
  src/api/urls.py
  src/api/v1/__init__.py
  src/api/v1/push_notifications/__init__.py
  src/api/v1/push_notifications/schemas.py
  src/api/v1/push_notifications/urls.py
  src/api/v1/push_notifications/views.py
  src/api/v1/urls.py
  src/app/drf/fields.py
  src/app/drf/utils.py
  src/app/drf/viewsets.py
  src/app/settings/conf.py
  src/app/urls.py
  src/push_notifications/services.py
  src/push_notifications/tasks.py
Labels: bug, enhancement

#25 Nginx static files / Translations
  infra/nginx/conf.d/fallback_server.conf
  infra/nginx/vhost.d/default
  infra/server/start_nginx_acme.sh
  local.yml
  production.yml
  staging.yml
Labels: bug
